### PR TITLE
add nanapore protocol docucment into MIRA Docs

### PR DESCRIPTION
**Pull request by rchau88**
I've added a quick fix to include pdf documents into MIRA Docs (see screenshot below). Let me know if this works with you

image

@nbx0 @kristinelacek

### CODE REVIEW

**Comment by kristinelacek** [comment]
wow looks a lot less painful than what I implemented!! Can you do it for the other 2 protocols as well? And add them as tabs inside of the Lab Protocols dropdown?

**Comment by nbx0** [comment]
This looks great and makes a lot more sense for maintenance than converting into html. @rchau88 is this the way both Flu and SC2 SOPs are displayed on their respective links? My quick scan of changes seemed like just sc2? Once both links show this sweet PDF viewer/downloader (instead of the html, sorry KL!), we will be to do merge to prod. Thanks!

**Comment by rchau88** [comment]
> wow looks a lot less painful than what I implemented!! Can you do it for the other 2 protocols as well? And add them as tabs inside of the Lab Protocols dropdown?

**Comment by rchau88** [comment]
> wow looks a lot less painful than what I implemented!! Can you do it for the other 2 protocols as well? And add them as tabs inside of the Lab Protocols dropdown?

Sure thing. Would you share with me the other protocols you want me to add?

**Comment by rchau88** [comment]
> This looks great and makes a lot more sense for maintenance than converting into html. @rchau88 is this the way both Flu and SC2 SOPs are displayed on their respective links? My quick scan of changes seemed like just sc2? Once both links show this sweet PDF viewer/downloader (instead of the html, sorry KL!), we will be to do merge to prod. Thanks!

Yes. Right now, it is display as separate links, but you can add it as hyperlinks and display it as separate page

**Pull request closed without merging**
